a_lr: 0.0001
algo: ddpg
batch_size: 64
buffer_size: 100000
c_lr: 0.0001
episode_length: 0
epsilon: 0.5
epsilon_speed: 0.99998
gamma: 0.95
load_model: false
load_model_run: 2
load_model_run_episode: 4000
log_dir: '20240815_213434'
max_episodes: 10
model_episode: 0
output_activation: softmax
save_interval: 5
seed: 1
tau: 0.001
